---
triple:          'arm64-apple-darwin'
binary-path:     stack
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _foo, symObjAddr: 0x0, symBinAddr: 0x100003F10, symSize: 0x4C }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _foo, symObjAddr: 0x0, symBinAddr: 0x100003F10, symSize: 0x4C }
  - { offsetInCU: 0x81, offset: 0x81, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x4C, symBinAddr: 0x100003F5C, symSize: 0x34 }
...
